# Configuration file for SCB of patch Management Project
# v2.0.0
# Database configuration
[database]
    [database.cred]
    username = "postgres"
    password = "password"
    host = "localhost"
    port = 5432
    database = "tae_pgdb"

    [database.tables]
    crapprovaldata_tbl = "crapprovaldata"
    settings_tbl = "settings"
    lgodetails_tbl = "logdetails"

# RabbitMQ configuration
[rabbitmq]

    [rabbitmq.noccom_producer]
    port = 5672 
    host = "127.0.0.1"
    queue = "tae_queue"
    routing_key = "tae.schedule"

    [rabbitmq.scb_consumer]
    port = 5672 
    host = "127.0.0.1"
    queue = "tae_queue"
    routing_key = "tae.schedule"
    
    [rabbitmq.scb_producer]
    host = "127.0.0.1"
    port = 5672 
    queue = "tae_queue"
    routing_key = "tae.status"

# Message type configuration
[messagetype]
    schedule_data = "161001"
    status_data = "162001"

# API configuration
[api]

    # Postgres API
    [api.postgres]
    host = "127.0.0.1"
    port = 5432

    # TAE to Agent API
    [api.tae_to_agent]
    host = "127.0.0.1"
    port = 8443

# Logging configuration
[log]

    # Status log path
    [log.status_log_path]
    status_log_path = "F:/patch-managment-project-16/patch_main/patch_management_scb_setup/patchmgt/scb_setup/storage/status_files"

    # API log paths
    [log.api_log_path]
        [log.api_log_path.tae_to_agent]
        get_schedule_path = "F:/patch-managment-project-16/patch_main/patch_management_scb_setup/patchmgt/scb_setup/logs/api_logs/tae_to_agent/get_schedule_data.log"
        status_log_upload_path = "F:/patch-managment-project-16/patch_main/patch_management_scb_setup/patchmgt/scb_setup/logs/api_logs/tae_to_agent/status_upload_log_data.log"

    # Rabitmq Service path
    [log.rabbitmq_log_path]
    scb_consumer_log_path = "F:/patch-managment-project-16/patch_main/patch_management_scb_setup/patchmgt/scb_setup/logs/rabitmq_service_logs/scb_consumer_log.log"
    scb_producer_log_path = "F:/patch-managment-project-16/patch_main/patch_management_scb_setup/patchmgt/scb_setup/logs/rabitmq_service_logs/scb_producer_log.log"
