# Configuration file for SCB of patch Management Project

# Database configuration
[database]
username = "postgres"
password = "postgres"
host = "localhost"
port = 5432
database = "scb_trial_db"

# RabbitMQ configuration
[rabbitmq]

    [rabbitmq.noccom_producer]
    port = 5672 
    host = "0.0.0.0"
    queue = "hello"
    routing_key = "hello"

    [rabbitmq.scb_consumer]
    port = 5672 
    host = "0.0.0.0"
    queue = "hello"
    routing_key = "hello"
    
    [rabbitmq.scb_producer]
    host = "0.0.0.0"
    port = 5672 
    queue = "bye"
    routing_key = "bye"

# API configuration
[api]

    # Postgres API
    [api.postgres]
    host = "0.0.0.0"
    port = 5432

    # TAE to Agent API
    [api.tae_to_agent]
    host = "0.0.0.0"
    port = 8443

# Logging configuration
[log]

    # Status log path
    [log.status_log_path]
    status_log_path = "/root/scb_dev/patch-management-scripting/patchmgt/scb_setup/storage/status_files"

    # API log paths
    [log.api_log_path]
        [log.api_log_path.tae_to_agent]
        get_schedule_path = "/root/scb_dev/patch-management-scripting/patchmgt/scb_setup/logs/api_logs/tae_to_agent/get_schedule_data.log"
        status_log_upload_path = "/root/scb_dev/patch-management-scripting/patchmgt/scb_setup/logs/api_logs/tae_to_agent/status_upload_log_data.log"

    # Rabitmq Service path
    [log.rabbitmq_log_path]
    scb_consumer_log_path = "/root/scb_dev/patch-management-scripting/patchmgt/scb_setup/logs/rabitmq_service_logs/scb_consumer_log.log"
    scb_producer_log_path = "/root/scb_dev/patch-management-scripting/patchmgt/scb_setup/logs/rabitmq_service_logs/scb_producer_log.log"
